version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
      - postgres_data:/bitnami/postgresql

  # app:
  #   image: 'oven/bun'
  #   entrypoint: []
  #   command: "/bin/sh -c 'sleep 10 && bun install && bun dev'"
  #   ports: ['3333:3333']
  #   volumes: ['./:/home/bun/app']
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
